config/routes.rb
OneWeek::Application.routes.draw do
  resources :todos
  root to: "todos#index"
end

app/models/todo.rb
class Todo < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    # TODO Write this method
    @todos = Todo.unfinished
  end

  def show
    @todo = Todo.find(params[:id])
  end

  def new
    @todo = Todo.new
  end

  def create
    todo = Todo.new(todo_params)
    todo.save
    redirect_to todos_path
  end

  def edit
    @todo = Todo.find(params[:id])
    render "new"
  end

  def update
    @todo = Todo.find(params[:id])
    @todo.update_attributes(todo_params)
    redirect_to todos_path
  end

  def destroy
    @todo = Todo.find(params[:id]).destroy
    redirect_to todos_path, flash: { notice: "Successfully deleted: #{@todo.name}" }
  end

  private

  def todo_params
    params.require(:todo).permit(:name, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>OneWeek</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/todos/_form.html.erb
<%= form_for @todo do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/todos/index.html.erb
<h1> Welcome to the official To Do app (copyright pending) </h1>

<% if flash[:notice] %>
  <div> <%= flash[:notice] %> </div>
<% end %>

<ul>
  <% @todos.each do |todo| %>
    <li> <%= todo.name %>
      <button> <%= link_to "edit", edit_todo_path(todo) %> </button>
      <button> <%= link_to "delete", todo_path(todo), { method: :delete } %> </button>
      <button> <%= link_to "finish", todo_path(todo, { status: "finished" }), {method: :put} %> </button>
   </li>
  <% end %>
 </ul>
 <div> <%= link_to "Create New ToDo", new_todo_path %> </div>

app/views/todos/new.html.erb
<h1> ON THE NEW PAGE </h1>

<%= render partial: 'form' %>

app/views/todos/show.html.erb
<%= @todo.name %>